### Installation

In [74]:
# pip install world-bank-data
# pip install world_bank_data --upgrade
# https://pypi.org/project/world-bank-data/ (All the thing are here)
# https://data.worldbank.org/products/third-party-apps (Third Party Apps)

### topics, sources, countries, regions, incomelevels, lendingtypes, indicators, search, language

In [75]:
# import pandas as pd
# import world_bank_data as wb
# pd.set_option('display.max_rows', 6)
# wb.get_topics()
# wb.get_sources()
# wb.get_countries()
# wb.get_regions()
# wb.get_incomelevels
# wb.get_lendingtypes()
# wb.get_indicators()
# wb.search_countries()
# wb.get_series('SP.POP.TOTL', date='2016', id_or_value='id', simplify_index=True)
# wb.options.language = "en"

In [76]:
import pandas as pd
import world_bank_data as wb
pd.set_option('display.max_rows', 25)

In [77]:
wb.get_topics()

,value,sourceNote
id,,
1,Agriculture & Rural Development,For the 70 percent of the world's poor who liv...
2,Aid Effectiveness,Aid effectiveness is the impact that aid has i...
3,Economy & Growth,Economic growth is central to economic develop...
4,Education,Education is one of the most powerful instrume...
5,Energy & Mining,The world economy needs ever-increasing amount...
6,Environment,Natural and man-made environmental resources –...
7,Financial Sector,An economy's financial markets are critical to...
8,Health,Improving health is central to the Millennium ...
9,Infrastructure,Infrastructure helps determine the success of ...
10,Social Protection & Labor,The supply of labor available in an economy in...
11,Poverty,For countries with an active poverty monitorin...
12,Private Sector,"Private markets drive economic growth, tapping..."
13,Public Sector,Effective governments improve people's standar...
14,Science & Technology,"Technological innovation, often fueled by gove..."
15,Social Development,"Data here cover child labor, gender issues, re..."
16,Urban Development,Cities can be tremendously efficient. It is ea...
17,Gender,Gender equality is a core development objectiv...
18,Millenium development goals,
19,Climate Change,Climate change is expected to hit developing c...
20,External Debt,Debt statistics provide a detailed picture of ...
21,Trade,Trade is a key means to fight poverty and achi...

In [78]:
wb.get_sources()

,lastupdated,name,code,description,url,dataavailability,metadataavailability,concepts
id,,,,,,,,
1,2021-08-18,Doing Business,DBS,,,Y,Y,3
2,2022-07-20,World Development Indicators,WDI,,,Y,Y,3
3,2021-09-27,Worldwide Governance Indicators,WGI,,,Y,Y,3
5,2016-03-21,Subnational Malnutrition Database,SNM,,,Y,Y,3
6,2022-01-14,International Debt Statistics,IDS,,,Y,Y,4
...,...,...,...,...,...,...,...,...
84,2022-07-19,Education Policy,EDP,,,Y,Y,3
85,2022-07-06,PEFA_2021_SNG,SNG,,,Y,N,4
86,2021-09-24,Global Jobs Indicators Database (JOIN),JON,,,Y,Y,3
87,2022-06-10,Country Climate and Development Report (CCDR),CCD,,,Y,Y,3
88,2022-07-05,Food Prices for Nutrition,FPN,,,Y,Y,4

In [79]:
wb.get_countries()

,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
id,,,,,,,,,
ABW,AW,Aruba,Latin America & Caribbean,,High income,Not classified,Oranjestad,-70.0167,12.5167
AFE,ZH,Africa Eastern and Southern,Aggregates,,Aggregates,Aggregates,,NaN,NaN
AFG,AF,Afghanistan,South Asia,South Asia,Low income,IDA,Kabul,69.1761,34.5228
AFR,A9,Africa,Aggregates,,Aggregates,Aggregates,,NaN,NaN
AFW,ZI,Africa Western and Central,Aggregates,,Aggregates,Aggregates,,NaN,NaN
...,...,...,...,...,...,...,...,...,...
XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,,Aggregates,Aggregates,,NaN,NaN
YEM,YE,"Yemen, Rep.",Middle East & North Africa,Middle East & North Africa (excluding high inc...,Low income,IDA,Sana'a,44.2075,15.3520
ZAF,ZA,South Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Upper middle income,IBRD,Pretoria,28.1871,-25.7460
ZMB,ZM,Zambia,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Low income,IDA,Lusaka,28.2937,-15.3982
ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,Harare,31.0672,-17.8312

In [80]:
wb.get_regions()

   code iso2code                                               name
id
    AFE       ZH                        Africa Eastern and Southern
    AFR       A9                                             Africa
    AFW       ZI                         Africa Western and Central
    ARB       1A                                         Arab World
    CAA       C9            Sub-Saharan Africa (IFC classification)
..  ...      ...                                                ...
9   SSF       ZG                                Sub-Saharan Africa
    SST       S1                                       Small states
    SXZ       A4          Sub-Saharan Africa excluding South Africa
    WLD       1W                                              World
    XZN       A5  Sub-Saharan Africa excluding South Africa and ...

[44 rows x 3 columns]

In [81]:
wb.get_incomelevels()

    iso2code                value
id
HIC       XD          High income
INX       XY       Not classified
LIC       XM           Low income
LMC       XN  Lower middle income
LMY       XO  Low & middle income
MIC       XP        Middle income
UMC       XT  Upper middle income

In [82]:
wb.get_lendingtypes()

    iso2code           value
id
IBD       XF            IBRD
IDB       XH           Blend
IDX       XI             IDA
LNX       XX  Not classified

In [83]:
wb.get_indicators()

,name,unit,source,sourceNote,sourceOrganization,topics
id,,,,,,
1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,Poverty
1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,Poverty
1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,Poverty
1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of data from Nation...,Poverty
1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,Poverty
...,...,...,...,...,...,...
WP15163_4.3,"Mobile account, female (% age 15+)",,WDI Database Archives,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...","Financial Sector ,Gender"
WP15163_4.8,"Mobile account, income, poorest 40% (% ages 15+)",,WDI Database Archives,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...",Financial Sector
WP15163_4.9,"Mobile account, income, richest 60% (% ages 15+)",,WDI Database Archives,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...",Financial Sector
wpremia_F,Wage Premia for Females (the ratio of skilled ...,,Gender Disaggregated Labor Database (GDLD),,,
wpremia_M,Wage Premia for Males (the ratio of skilled m...,,Gender Disaggregated Labor Database (GDLD),,,

In [84]:
wb.get_indicators(topic=3, source=2)
# topic and source id are from get_topics/get_sources

,name,unit,source,sourceNote,sourceOrganization,topics
id,,,,,,
BG.GSR.NFSV.GD.ZS,Trade in services (% of GDP),,World Development Indicators,Trade in services is the sum of service export...,"International Monetary Fund, Balance of Paymen...","Economy & Growth,Private Sector,Trade"
BM.GSR.CMCP.ZS,"Communications, computer, etc. (% of service i...",,World Development Indicators,"Communications, computer, information, and oth...","International Monetary Fund, Balance of Paymen...","Economy & Growth,Trade"
BM.GSR.FCTY.CD,"Primary income payments (BoP, current US$)",,World Development Indicators,Primary income payments refer to employee comp...,"International Monetary Fund, Balance of Paymen...",Economy & Growth
BM.GSR.GNFS.CD,"Imports of goods and services (BoP, current US$)",,World Development Indicators,Imports of goods and services comprise all tra...,"International Monetary Fund, Balance of Paymen...","Economy & Growth,Trade"
BM.GSR.INSF.ZS,Insurance and financial services (% of service...,,World Development Indicators,Insurance and financial services cover various...,"International Monetary Fund, Balance of Paymen...","Economy & Growth,Private Sector,Trade"
...,...,...,...,...,...,...
NY.TTF.GNFS.KN,Terms of trade adjustment (constant LCU),,World Development Indicators,The terms of trade effect equals capacity to i...,"World Bank national accounts data, and OECD Na...",Economy & Growth
PA.NUS.ATLS,DEC alternative conversion factor (LCU per US$),,World Development Indicators,The DEC alternative conversion factor is the u...,"International Monetary Fund, International Fin...","Economy & Growth,Financial Sector"
PA.NUS.PPP,"PPP conversion factor, GDP (LCU per internatio...",,World Development Indicators,Purchasing power parity (PPP) conversion facto...,"International Comparison Program, World Bank |...",Economy & Growth
PA.NUS.PPPC.RF,Price level ratio of PPP conversion factor (GD...,,World Development Indicators,Price level ratio is the ratio of a purchasing...,"International Comparison Program, World Bank |...",Economy & Growth
PA.NUS.PRVT.PP,"PPP conversion factor, private consumption (LC...",,World Development Indicators,Purchasing power parity (PPP) conversion facto...,"International Comparison Program, World Bank |...",Economy & Growth

In [85]:
wb.search_indicators('mathematics')
# wb.search_countries('mathematics')
# wb.search_source('mathematics')

,name,unit,source,sourceNote,sourceOrganization,topics
id,,,,,,
2.0.cov.Math.pl_2.all,Coverage: Mathematics Proficiency Level 2,,LAC Equity Lab,The coverage rate is the childhood access rate...,LAC Equity Lab tabulations using PISA Data.,Poverty
2.0.cov.Math.pl_2.prv,"Coverage: Mathematics Proficiency Level 2, Pri...",,LAC Equity Lab,The coverage rate is the childhood access rate...,LAC Equity Lab tabulations using PISA Data.,Poverty
2.0.cov.Math.pl_2.pub,"Coverage: Mathematics Proficiency Level 2, Pub...",,LAC Equity Lab,The coverage rate is the childhood access rate...,LAC Equity Lab tabulations using PISA Data.,Poverty
2.0.cov.Math.pl_3.all,Coverage: Mathematics Proficiency Level 3,,LAC Equity Lab,The coverage rate is the childhood access rate...,LAC Equity Lab tabulations using PISA Data.,Poverty
2.0.cov.Math.pl_3.prv,"Coverage: Mathematics Proficiency Level 3, Pri...",,LAC Equity Lab,The coverage rate is the childhood access rate...,LAC Equity Lab tabulations using PISA Data.,Poverty
...,...,...,...,...,...,...
UIS.MATH.PRIMARY.NONNATIVE,Proportion of students at the end of primary e...,,Education Statistics,,,
UIS.MATH.PRIMARY.NPIA,Proportion of students at the end of primary e...,,Education Statistics,,,
UIS.MATH.PRIMARY.RURAL,Proportion of students at the end of primary e...,,Education Statistics,,,
UIS.MATH.PRIMARY.URBAN,Proportion of students at the end of primary e...,,Education Statistics,,,
UIS.MATH.PRIMARY.WPIA,Proportion of students at the end of primary a...,,Education Statistics,,,

In [86]:
# wb.get_series('SP.POP.TOTL', mrv=1)
    # The result above has a 3-dimensional index.
    # Use the argument simplify_index
    # to ignore the dimensions that take a single value (here: year and series).
    # Also, use the argument id_or_value='id'
    # if you prefer your data to be indexed by the codes rather than labels:
# wb.get_series('SP.POP.TOTL', date='2016', id_or_value='id', simplify_index=True)
    # mrv, integer: one or more most recent values
    # date, string: either one year, or two years separated with a colon, like '2010:2018'
    # gapfill, string: 'Y' or 'N' (the default): forward fills missing values.

In [87]:
# Country and indicator description in non-English languages
wb.options.language = 'en'
wb.get_indicators('SP.POP.TOTL')

,name,unit,source,sourceNote,sourceOrganization,topics
id,,,,,,
SP.POP.TOTL,"Population, total",,World Development Indicators,Total population is based on the de facto defi...,(1) United Nations Population Division. World ...,"Climate Change,Health"

In [88]:
wb.get_series('SP.POP.TOTL', date='2010:2020', id_or_value='id', simplify_index=True)

Country  Year
AFE      2010    518468229.0
         2011    532760424.0
         2012    547482863.0
         2013    562601578.0
         2014    578075373.0
                    ...
ZWE      2016     14030338.0
         2017     14236599.0
         2018     14438812.0
         2019     14645473.0
         2020     14862927.0
Name: SP.POP.TOTL, Length: 2926, dtype: float64

In [89]:
wb.get_series('SP.POP.TOTL', date='2010:2020', id_or_value='id', simplify_index=True)

Country  Year
AFE      2010    518468229.0
         2011    532760424.0
         2012    547482863.0
         2013    562601578.0
         2014    578075373.0
                    ...
ZWE      2016     14030338.0
         2017     14236599.0
         2018     14438812.0
         2019     14645473.0
         2020     14862927.0
Name: SP.POP.TOTL, Length: 2926, dtype: float64

In [90]:
wb.get_topics()

,value,sourceNote
id,,
1,Agriculture & Rural Development,For the 70 percent of the world's poor who liv...
2,Aid Effectiveness,Aid effectiveness is the impact that aid has i...
3,Economy & Growth,Economic growth is central to economic develop...
4,Education,Education is one of the most powerful instrume...
5,Energy & Mining,The world economy needs ever-increasing amount...
6,Environment,Natural and man-made environmental resources –...
7,Financial Sector,An economy's financial markets are critical to...
8,Health,Improving health is central to the Millennium ...
9,Infrastructure,Infrastructure helps determine the success of ...
10,Social Protection & Labor,The supply of labor available in an economy in...
11,Poverty,For countries with an active poverty monitorin...
12,Private Sector,"Private markets drive economic growth, tapping..."
13,Public Sector,Effective governments improve people's standar...
14,Science & Technology,"Technological innovation, often fueled by gove..."
15,Social Development,"Data here cover child labor, gender issues, re..."
16,Urban Development,Cities can be tremendously efficient. It is ea...
17,Gender,Gender equality is a core development objectiv...
18,Millenium development goals,
19,Climate Change,Climate change is expected to hit developing c...
20,External Debt,Debt statistics provide a detailed picture of ...
21,Trade,Trade is a key means to fight poverty and achi...

In [91]:
wb.get_sources()

,lastupdated,name,code,description,url,dataavailability,metadataavailability,concepts
id,,,,,,,,
1,2021-08-18,Doing Business,DBS,,,Y,Y,3
2,2022-07-20,World Development Indicators,WDI,,,Y,Y,3
3,2021-09-27,Worldwide Governance Indicators,WGI,,,Y,Y,3
5,2016-03-21,Subnational Malnutrition Database,SNM,,,Y,Y,3
6,2022-01-14,International Debt Statistics,IDS,,,Y,Y,4
...,...,...,...,...,...,...,...,...
84,2022-07-19,Education Policy,EDP,,,Y,Y,3
85,2022-07-06,PEFA_2021_SNG,SNG,,,Y,N,4
86,2021-09-24,Global Jobs Indicators Database (JOIN),JON,,,Y,Y,3
87,2022-06-10,Country Climate and Development Report (CCDR),CCD,,,Y,Y,3
88,2022-07-05,Food Prices for Nutrition,FPN,,,Y,Y,4

In [92]:
wb.get_indicators(topic=13)

,name,unit,source,sourceNote,sourceOrganization,topics
id,,,,,,
GB.TAX.CMAR.ZS,"Highest marginal tax rate, corporate rate (%)",,Africa Development Indicators,Highest marginal tax rate (corporate rate) is ...,KPMG's Corporate and Indirect Tax Rate Survey ...,Public Sector
GC.AST.TOTL.CN,Net acquisition of financial assets (current LCU),,World Development Indicators,Net acquisition of government financial assets...,"International Monetary Fund, Government Financ...",Public Sector
GC.AST.TOTL.GD.ZS,Net acquisition of financial assets (% of GDP),,World Development Indicators,Net acquisition of government financial assets...,"International Monetary Fund, Government Financ...",Public Sector
GC.DOD.TOTL.CN,"Central government debt, total (current LCU)",,World Development Indicators,Debt is the entire stock of direct government ...,"International Monetary Fund, Government Financ...",Public Sector
GC.DOD.TOTL.GD.ZS,"Central government debt, total (% of GDP)",,World Development Indicators,Debt is the entire stock of direct government ...,"International Monetary Fund, Government Financ...","Economy & Growth,Public Sector"
...,...,...,...,...,...,...
VC.IDP.TOTL.LE,"Internally displaced persons (number, low esti...",,Africa Development Indicators,Internally displaced persons are people or gro...,Internal Displacement Monitoring Centre.,Public Sector
VC.IHR.PSRC.FE.P5,"Intentional homicides, female (per 100,000 fem...",,World Development Indicators,"Intentional homicides, female are estimates of...",UN Office on Drugs and Crime's International H...,Public Sector
VC.IHR.PSRC.MA.P5,"Intentional homicides, male (per 100,000 male)",,World Development Indicators,"Intentional homicides, male are estimates of u...",UN Office on Drugs and Crime's International H...,Public Sector
VC.IHR.PSRC.P5,"Intentional homicides (per 100,000 people)",,World Development Indicators,Intentional homicides are estimates of unlawfu...,UN Office on Drugs and Crime's International H...,Public Sector
VC.PKP.TOTL.UN,"Presence of peace keepers (number of troops, p...",,WDI Database Archives,Presence of peacebuilders and peacekeepers are...,"UN Department of Peacekeeping Operations, http...",Public Sector

In [93]:
df = wb.get_series(indicator="GC.AST.TOTL.GD.ZS",
                   date="2002:2021",
                   country="TUR",
                   id_or_value="id",
                   simplify_index=True)
df

Year
2002         NaN
2003         NaN
2004         NaN
2005         NaN
2006         NaN
2007         NaN
2008    0.328401
2009    0.722857
2010   -0.315933
2011    1.011686
2012    0.896024
2013    0.910673
2014    1.079747
2015    1.595065
2016    0.995298
2017    0.893686
2018    0.870535
2019    2.109354
2020    4.275715
2021         NaN
Name: GC.AST.TOTL.GD.ZS, dtype: float64

In [94]:
wb.search_countries("TUR")

,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
id,,,,,,,,,
TCA,TC,Turks and Caicos Islands,Latin America & Caribbean,,High income,Not classified,Grand Turk,-71.141389,21.460278
TKM,TM,Turkmenistan,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Ashgabat,58.379400,37.950900
TUR,TR,Turkiye,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Ankara,32.360600,39.715300